AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/{rails,rake}'
  - !ruby/regexp /old_and_unused\.rb$/
  - '**/*.erb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true